/**
 * Saudi-market make/model catalog, bilingual.
 *
 * Haraj does not expose a catalog, makes and models live only inside free-form
 * tags there, so this is curated rather than imported. It covers the brands
 * actually sold and rented in the Kingdom, including the Chinese marques that
 * have taken real share recently.
 *
 * It is not meant to be exhaustive forever: an agency that needs something
 * missing picks "Other", types it, and the entry lands in the admin's catalog
 * queue to be promoted. The list improves from real usage instead of guesswork.
 */

export type SeedMake = {
  code: string
  nameEn: string
  nameAr: string
  models: [code: string, nameEn: string, nameAr: string][]
}

export const CATALOG: SeedMake[] = [
  {
    code: "TOYOTA",
    nameEn: "Toyota",
    nameAr: "تويوتا",
    models: [
      ["CAMRY", "Camry", "كامري"],
      ["COROLLA", "Corolla", "كورولا"],
      ["YARIS", "Yaris", "يارس"],
      ["LAND_CRUISER", "Land Cruiser", "لاندكروزر"],
      ["PRADO", "Prado", "برادو"],
      ["FORTUNER", "Fortuner", "فورتشنر"],
      ["HILUX", "Hilux", "هايلكس"],
      ["RAV4", "RAV4", "راف فور"],
      ["AVALON", "Avalon", "افالون"],
      ["INNOVA", "Innova", "إنوفا"],
      ["HIACE", "Hiace", "هايس"],
      ["RUSH", "Rush", "راش"],
      ["COASTER", "Coaster", "كوستر"],
      ["SEQUOIA", "Sequoia", "سيكويا"],
      ["CHR", "C-HR", "سي اتش ار"],
      ["CROWN", "Crown", "كراون"],
      ["RAIZE", "Raize", "رايز"],
    ],
  },
  {
    code: "HYUNDAI",
    nameEn: "Hyundai",
    nameAr: "هيونداي",
    models: [
      ["ACCENT", "Accent", "اكسنت"],
      ["ELANTRA", "Elantra", "النترا"],
      ["SONATA", "Sonata", "سوناتا"],
      ["TUCSON", "Tucson", "توسان"],
      ["SANTA_FE", "Santa Fe", "سنتافي"],
      ["CRETA", "Creta", "كريتا"],
      ["PALISADE", "Palisade", "باليسيد"],
      ["AZERA", "Azera", "ازيرا"],
      ["VENUE", "Venue", "فينيو"],
      ["STARIA", "Staria", "ستاريا"],
      ["H1", "H1", "اتش 1"],
      ["IONIQ", "Ioniq", "ايونيك"],
    ],
  },
  {
    code: "NISSAN",
    nameEn: "Nissan",
    nameAr: "نيسان",
    models: [
      ["SUNNY", "Sunny", "صني"],
      ["ALTIMA", "Altima", "التيما"],
      ["MAXIMA", "Maxima", "ماكسيما"],
      ["PATROL", "Patrol", "باترول"],
      ["XTERRA", "Xterra", "اكستيرا"],
      ["X_TRAIL", "X-Trail", "اكس تريل"],
      ["KICKS", "Kicks", "كيكس"],
      ["PATHFINDER", "Pathfinder", "باثفندر"],
      ["NAVARA", "Navara", "نافارا"],
      ["URVAN", "Urvan", "ايرفان"],
    ],
  },
  {
    code: "KIA",
    nameEn: "Kia",
    nameAr: "كيا",
    models: [
      ["RIO", "Rio", "ريو"],
      ["CERATO", "Cerato", "سيراتو"],
      ["K5", "K5", "كي 5"],
      ["OPTIMA", "Optima", "اوبتيما"],
      ["SPORTAGE", "Sportage", "سبورتاج"],
      ["SORENTO", "Sorento", "سورينتو"],
      ["SELTOS", "Seltos", "سيلتوس"],
      ["CARNIVAL", "Carnival", "كرنفال"],
      ["TELLURIDE", "Telluride", "تيلورايد"],
      ["PEGAS", "Pegas", "بيجاس"],
    ],
  },
  {
    code: "CHEVROLET",
    nameEn: "Chevrolet",
    nameAr: "شفروليه",
    models: [
      ["TAHOE", "Tahoe", "تاهو"],
      ["SUBURBAN", "Suburban", "سبربان"],
      ["SILVERADO", "Silverado", "سلفرادو"],
      ["TRAVERSE", "Traverse", "ترافيرس"],
      ["MALIBU", "Malibu", "ماليبو"],
      ["IMPALA", "Impala", "امبالا"],
      ["CAPTIVA", "Captiva", "كابتيفا"],
      ["TRAILBLAZER", "Trailblazer", "تريل بليزر"],
      ["GROOVE", "Groove", "جروف"],
      ["CAPRICE", "Caprice", "كابرس"],
    ],
  },
  {
    code: "FORD",
    nameEn: "Ford",
    nameAr: "فورد",
    models: [
      ["F150", "F-150", "اف 150"],
      ["EXPEDITION", "Expedition", "اكسبديشن"],
      ["EXPLORER", "Explorer", "اكسبلورر"],
      ["TAURUS", "Taurus", "توروس"],
      ["EDGE", "Edge", "ايدج"],
      ["ESCAPE", "Escape", "اسكيب"],
      ["MUSTANG", "Mustang", "موستنج"],
      ["RANGER", "Ranger", "رينجر"],
      ["BRONCO", "Bronco", "برونكو"],
      ["TERRITORY", "Territory", "تيريتوري"],
    ],
  },
  {
    code: "GMC",
    nameEn: "GMC",
    nameAr: "جي ام سي",
    models: [
      ["YUKON", "Yukon", "يوكن"],
      ["SIERRA", "Sierra", "سييرا"],
      ["ACADIA", "Acadia", "اكاديا"],
      ["TERRAIN", "Terrain", "تيرين"],
      ["CANYON", "Canyon", "كانيون"],
    ],
  },
  {
    code: "LEXUS",
    nameEn: "Lexus",
    nameAr: "لكزس",
    models: [
      ["ES", "ES", "اي اس"],
      ["IS", "IS", "اي اس"],
      ["LS", "LS", "ال اس"],
      ["GS", "GS", "جي اس"],
      ["LX", "LX", "ال اكس"],
      ["GX", "GX", "جي اكس"],
      ["RX", "RX", "ار اكس"],
      ["NX", "NX", "ان اكس"],
      ["UX", "UX", "يو اكس"],
    ],
  },
  {
    code: "MERCEDES",
    nameEn: "Mercedes-Benz",
    nameAr: "مرسيدس",
    models: [
      ["C_CLASS", "C-Class", "الفئة C"],
      ["E_CLASS", "E-Class", "الفئة E"],
      ["S_CLASS", "S-Class", "الفئة S"],
      ["G_CLASS", "G-Class", "جي كلاس"],
      ["GLC", "GLC", "جي ال سي"],
      ["GLE", "GLE", "جي ال اي"],
      ["GLS", "GLS", "جي ال اس"],
      ["A_CLASS", "A-Class", "الفئة A"],
      ["CLA", "CLA", "سي ال اي"],
      ["V_CLASS", "V-Class", "الفئة V"],
    ],
  },
  {
    code: "BMW",
    nameEn: "BMW",
    nameAr: "بي ام دبليو",
    models: [
      ["SERIES_3", "3 Series", "الفئة الثالثة"],
      ["SERIES_5", "5 Series", "الفئة الخامسة"],
      ["SERIES_7", "7 Series", "الفئة السابعة"],
      ["X1", "X1", "اكس 1"],
      ["X3", "X3", "اكس 3"],
      ["X5", "X5", "اكس 5"],
      ["X6", "X6", "اكس 6"],
      ["X7", "X7", "اكس 7"],
      ["I_SERIES", "i Series", "الفئة i"],
    ],
  },
  {
    code: "HONDA",
    nameEn: "Honda",
    nameAr: "هوندا",
    models: [
      ["ACCORD", "Accord", "اكورد"],
      ["CIVIC", "Civic", "سيفيك"],
      ["CRV", "CR-V", "سي ار في"],
      ["PILOT", "Pilot", "بايلوت"],
      ["CITY", "City", "سيتي"],
      ["HRV", "HR-V", "اتش ار في"],
      ["ODYSSEY", "Odyssey", "اوديسي"],
    ],
  },
  {
    code: "MAZDA",
    nameEn: "Mazda",
    nameAr: "مازدا",
    models: [
      ["MAZDA_3", "Mazda 3", "مازدا 3"],
      ["MAZDA_6", "Mazda 6", "مازدا 6"],
      ["CX3", "CX-3", "سي اكس 3"],
      ["CX5", "CX-5", "سي اكس 5"],
      ["CX9", "CX-9", "سي اكس 9"],
    ],
  },
  {
    code: "MITSUBISHI",
    nameEn: "Mitsubishi",
    nameAr: "ميتسوبيشي",
    models: [
      ["LANCER", "Lancer", "لانسر"],
      ["ATTRAGE", "Attrage", "اتراج"],
      ["PAJERO", "Pajero", "باجيرو"],
      ["MONTERO", "Montero Sport", "مونتيرو"],
      ["L200", "L200", "ال 200"],
      ["ASX", "ASX", "اي اس اكس"],
      ["XPANDER", "Xpander", "اكسباندر"],
    ],
  },
  {
    code: "MG",
    nameEn: "MG",
    nameAr: "ام جي",
    models: [
      ["MG5", "MG5", "ام جي 5"],
      ["MG6", "MG6", "ام جي 6"],
      ["ZS", "ZS", "زد اس"],
      ["HS", "HS", "اتش اس"],
      ["RX8", "RX8", "ار اكس 8"],
      ["GT", "GT", "جي تي"],
    ],
  },
  {
    code: "CHANGAN",
    nameEn: "Changan",
    nameAr: "شانجان",
    models: [
      ["CS35", "CS35", "سي اس 35"],
      ["CS75", "CS75", "سي اس 75"],
      ["CS85", "CS85", "سي اس 85"],
      ["EADO", "Eado", "ايدو"],
      ["ALSVIN", "Alsvin", "الســفن"],
      ["UNI_T", "UNI-T", "يوني تي"],
    ],
  },
  {
    code: "GEELY",
    nameEn: "Geely",
    nameAr: "جيلي",
    models: [
      ["EMGRAND", "Emgrand", "امجراند"],
      ["COOLRAY", "Coolray", "كولراي"],
      ["AZKARRA", "Azkarra", "ازكارا"],
      ["OKAVANGO", "Okavango", "اوكافانجو"],
      ["MONJARO", "Monjaro", "مونجارو"],
    ],
  },
  {
    code: "CHERY",
    nameEn: "Chery",
    nameAr: "شيري",
    models: [
      ["TIGGO_4", "Tiggo 4", "تيجو 4"],
      ["TIGGO_7", "Tiggo 7", "تيجو 7"],
      ["TIGGO_8", "Tiggo 8", "تيجو 8"],
      ["ARRIZO", "Arrizo", "اريزو"],
    ],
  },
  {
    code: "JETOUR",
    nameEn: "Jetour",
    nameAr: "جيتور",
    models: [
      ["X70", "X70", "اكس 70"],
      ["X90", "X90", "اكس 90"],
      ["DASHING", "Dashing", "داشينج"],
      ["T2", "T2", "تي 2"],
    ],
  },
  {
    code: "HAVAL",
    nameEn: "Haval",
    nameAr: "هافال",
    models: [
      ["H6", "H6", "اتش 6"],
      ["JOLION", "Jolion", "جوليون"],
      ["DARGO", "Dargo", "دارجو"],
      ["H9", "H9", "اتش 9"],
    ],
  },
  {
    code: "GAC",
    nameEn: "GAC",
    nameAr: "جي ايه سي",
    models: [
      ["GS3", "GS3", "جي اس 3"],
      ["GS4", "GS4", "جي اس 4"],
      ["GS8", "GS8", "جي اس 8"],
      ["EMPOW", "Empow", "امباو"],
    ],
  },
  {
    code: "BYD",
    nameEn: "BYD",
    nameAr: "بي واي دي",
    models: [
      ["SEAL", "Seal", "سيل"],
      ["ATTO_3", "Atto 3", "اتو 3"],
      ["HAN", "Han", "هان"],
      ["SONG", "Song", "سونج"],
    ],
  },
  {
    code: "SUZUKI",
    nameEn: "Suzuki",
    nameAr: "سوزوكي",
    models: [
      ["BALENO", "Baleno", "بالينو"],
      ["DZIRE", "Dzire", "دزاير"],
      ["ERTIGA", "Ertiga", "ارتيجا"],
      ["JIMNY", "Jimny", "جمني"],
      ["VITARA", "Vitara", "فيتارا"],
    ],
  },
  {
    code: "ISUZU",
    nameEn: "Isuzu",
    nameAr: "ايسوزو",
    models: [
      ["D_MAX", "D-Max", "دي ماكس"],
      ["MU_X", "MU-X", "ام يو اكس"],
    ],
  },
  {
    code: "INFINITI",
    nameEn: "Infiniti",
    nameAr: "انفينيتي",
    models: [
      ["Q50", "Q50", "كيو 50"],
      ["QX60", "QX60", "كيو اكس 60"],
      ["QX80", "QX80", "كيو اكس 80"],
    ],
  },
  {
    code: "CADILLAC",
    nameEn: "Cadillac",
    nameAr: "كاديلاك",
    models: [
      ["ESCALADE", "Escalade", "اسكاليد"],
      ["XT5", "XT5", "اكس تي 5"],
      ["CT5", "CT5", "سي تي 5"],
    ],
  },
  {
    code: "DODGE",
    nameEn: "Dodge",
    nameAr: "دودج",
    models: [
      ["CHARGER", "Charger", "تشارجر"],
      ["CHALLENGER", "Challenger", "تشالنجر"],
      ["DURANGO", "Durango", "دورانجو"],
    ],
  },
  {
    code: "JEEP",
    nameEn: "Jeep",
    nameAr: "جيب",
    models: [
      ["WRANGLER", "Wrangler", "رانجلر"],
      ["GRAND_CHEROKEE", "Grand Cherokee", "جراند شيروكي"],
      ["COMPASS", "Compass", "كومباس"],
      ["GLADIATOR", "Gladiator", "جلادييتر"],
    ],
  },
  {
    code: "LAND_ROVER",
    nameEn: "Land Rover",
    nameAr: "لاند روفر",
    models: [
      ["RANGE_ROVER", "Range Rover", "رنج روفر"],
      ["SPORT", "Range Rover Sport", "رنج روفر سبورت"],
      ["DEFENDER", "Defender", "ديفندر"],
      ["DISCOVERY", "Discovery", "ديسكفري"],
    ],
  },
  {
    code: "PORSCHE",
    nameEn: "Porsche",
    nameAr: "بورش",
    models: [
      ["CAYENNE", "Cayenne", "كايين"],
      ["MACAN", "Macan", "ماكان"],
      ["PANAMERA", "Panamera", "باناميرا"],
      ["911", "911", "911"],
    ],
  },
  {
    code: "AUDI",
    nameEn: "Audi",
    nameAr: "اودي",
    models: [
      ["A4", "A4", "اي 4"],
      ["A6", "A6", "اي 6"],
      ["A8", "A8", "اي 8"],
      ["Q5", "Q5", "كيو 5"],
      ["Q7", "Q7", "كيو 7"],
      ["Q8", "Q8", "كيو 8"],
    ],
  },
  {
    code: "VOLKSWAGEN",
    nameEn: "Volkswagen",
    nameAr: "فولكس واجن",
    models: [
      ["GOLF", "Golf", "جولف"],
      ["PASSAT", "Passat", "باسات"],
      ["TIGUAN", "Tiguan", "تيجوان"],
      ["TOUAREG", "Touareg", "طوارق"],
    ],
  },
  {
    code: "PEUGEOT",
    nameEn: "Peugeot",
    nameAr: "بيجو",
    models: [
      ["P301", "301", "301"],
      ["P3008", "3008", "3008"],
      ["P5008", "5008", "5008"],
    ],
  },
  {
    code: "RENAULT",
    nameEn: "Renault",
    nameAr: "رينو",
    models: [
      ["DUSTER", "Duster", "داستر"],
      ["KOLEOS", "Koleos", "كوليوس"],
      ["MEGANE", "Megane", "ميجان"],
    ],
  },
  {
    code: "TESLA",
    nameEn: "Tesla",
    nameAr: "تسلا",
    models: [
      ["MODEL_3", "Model 3", "موديل 3"],
      ["MODEL_Y", "Model Y", "موديل Y"],
      ["MODEL_S", "Model S", "موديل S"],
    ],
  },
  {
    code: "LUCID",
    nameEn: "Lucid",
    nameAr: "لوسيد",
    models: [
      ["AIR", "Air", "اير"],
      ["GRAVITY", "Gravity", "جرافيتي"],
    ],
  },
  {
    code: "VOLVO",
    nameEn: "Volvo",
    nameAr: "فولفو",
    models: [
      ["XC40", "XC40", "اكس سي 40"],
      ["XC60", "XC60", "اكس سي 60"],
      ["XC90", "XC90", "اكس سي 90"],
    ],
  },
  {
    code: "BENTLEY",
    nameEn: "Bentley",
    nameAr: "بنتلي",
    models: [
      ["BENTAYGA", "Bentayga", "بنتايجا"],
      ["CONTINENTAL", "Continental", "كونتيننتال"],
    ],
  },
  {
    code: "ROLLS_ROYCE",
    nameEn: "Rolls-Royce",
    nameAr: "رولز رويس",
    models: [
      ["CULLINAN", "Cullinan", "كولينان"],
      ["GHOST", "Ghost", "جوست"],
      ["PHANTOM", "Phantom", "فانتوم"],
    ],
  },
  {
    code: "JAC",
    nameEn: "JAC",
    nameAr: "جاك",
    models: [
      ["S3", "S3", "اس 3"],
      ["S4", "S4", "اس 4"],
      ["T8", "T8", "تي 8"],
    ],
  },
  {
    code: "EXEED",
    nameEn: "Exeed",
    nameAr: "اكسيد",
    models: [
      ["TXL", "TXL", "تي اكس ال"],
      ["VX", "VX", "في اكس"],
      ["LX", "LX", "ال اكس"],
    ],
  },
  {
    code: "OTHER",
    nameEn: "Other",
    nameAr: "أخرى",
    models: [["OTHER", "Other", "أخرى"]],
  },
]

